config: 4

# Model parameters
model_type: '5SHMR+scatter'
param_ini: [0.40, 0.20, 12.52, 10.916, 0.457, 0.566, 1.53] #Leauthaud 2012
param_low: [0.0, 0.0, 12.15, 10.716, 0.367, 0.0, -0.27 ] #ten sigma up (delta fixed at 0.0)
param_upp: [1.0, 1.0, 12.89, 11.116, 0.547, 0.9, 3.33] #ten sigma down (delta fixed at 0.9)
param_sig: [0.1, 0.1, 0.03, 0.02, 0.01, 0.01, 0.2 ] #one sigma


param_labels: ['scatter_model_param1',
               'scatter_model_param2',
               'smhm_m1_0',
               'smhm_m0_0',
               'smhm_beta_0',
               'smhm_delta_0',
               'smhm_gamma_0']
redshift_param_labels: ['smhm_m1_a',
                        'smhm_m0_a',
                        'smhm_beta_a',
                        'smhm_delta_a',
                        'smhm_gamma_a']
param_labels_latex: ['$\sigma_{12}$',
                     '$\sigma_{15}$',
                     '$\log_{10}(M_{1})$',
                     '$\log_{10}(M_{\star, 0})$',
                     '$\beta$',
                     '$\delta$',
                     '$\gamma$']

# model_type: 'scatter_only'
# param_ini: [0.4, 0.2]
# param_low: [0.00, 0.00]
# param_upp: [1.00, 1.00]
# param_sig: [0.10, 0.10]
# mcmc_param_labels: ['scatter_model_param1',
#                     'scatter_model_param2']

# MCMC Runs
mcmc_out_dir: 'MCMC/outfiles/'
mcmc_prefix: 'cosmos_bplanck'
mcmc_nthreads: 1
mcmc_nburnin: 50
mcmc_nwalkers_burnin: 30
mcmc_nsamples: 250
mcmc_nwalkers: 30
mcmc_smf_only: False
mcmc_wl_only: False
mcmc_wl_weight: 1.0
mcmc_ndims: 7
mcmc_moves_burnin: 'walk'
mcmc_moves: 'walk'
mcmc_stretch_a: 2.0
mcmc_live_dangerously: True #for testing on smaller walker size



#############################################################################
#DATA
data_location: '/Users/fardila/Documents/GitHub/dwarf_lensing/Data/'

# COSMOS
cosmos_dir: 'cosmos/'
cosmos_catalog_reference : 'Laigle+2016'

# dwarfs
cosmos_dwarf_file: 'dwarf_sample_for_paper.fits'

# SMF
cosmos_SMF_fit_file: 'cosmos2015_dic2017_smf_z01-04_STY0.dat'
cosmos_SMF_points_file: 'cosmos2015_dic2017_smf_z01-04_Vmax0_with_header.dat'

#weak lensing
cosmos_wl_file: 'dwarf_all_lens_laigle2015_nozp2.out'

# Useful information in the catalog
n_dwarfs: 6876
mean_mass: 8.52695
mean_z: 0.301442
n_objects_with_specz: 1153
frac_objects_with_specz: 0.167685

#cosmology
cosmos_h0 : 0.7
cosmos_omega_m: 0.3

#############################################################################
# Simulation
sim_dir: 'bplanck/'

sim_name : 'bolshoi-planck'
sim_halo_finder : 'rockstar'
sim_version_name : 'bplanck_dwarfs'
sim_ptcl_version_name : 'bplanck_dwarfs'

sim_z : 0.278625 #(1/0.78209)-1 ; a=0.78209
sim_lbox : 250.0 #Mpc/h
sim_particle_mass : 1.5e8
sim_particles_per_dimension: 2048

sim_wl_bins : >
              0.01 0.01598922 0.02947921 0.05184152 0.09251636 0.1643359
              0.29233885 0.51980176 0.92438561
sim_h0: 0.678
sim_omega_m: 0.307

sim_halo_cat_file: 'hlist_0.78209.list'
sim_output_fname : 'hlist_0.78209.hdf5'
sim_particle_file : 'bplanck_particles_100m_a0.78209.hdf5'
sim_columns_to_keep_dict : >
                          {'halo_id': (1, 'i8'), 'halo_upid': (6, 'i8'),
                          'halo_mvir': (10, 'f4'), 'halo_x': (17, 'f4'),
                          'halo_y': (18, 'f4'), 'halo_z': (19, 'f4'),
                          'halo_vx': (20, 'f4'), 'halo_vy': (21, 'f4'),
                          'halo_vz': (22, 'f4'), 'halo_rvir': (11, 'f4'),
                          'halo_mpeak': (60, 'f4')}
